version: "3"

x-flash-environment: &flash-environment
  AWS_ACCESS_KEY_ID: admin
  AWS_SECRET_ACCESS_KEY: password
  AWS_REGION: us-east-1
  CATALOG_WAREHOUSE: s3://warehouse/
  CATALOG_IO__IMPL: org.apache.iceberg.aws.s3.S3FileIO
  CATALOG_S3_ENDPOINT: http://minio:9000

networks:
  flash:
    driver: bridge

services:
  rest:
    image: tabulario/iceberg-rest:latest
    container_name: iceberg-rest
    networks:
      flash:
        aliases:
          - iceberg-rest.minio
    ports:
      - "8181:8181"
    environment:
      <<: *flash-environment

#  spark-iceberg:
#    image: tabulario/spark-iceberg
#    container_name: spark-iceberg
#    build: spark/
#    networks:
#      flash:
#    depends_on:
#      - rest
#      - minio
#    environment:
#      - AWS_ACCESS_KEY_ID=minioadmin
#      - AWS_SECRET_ACCESS_KEY=minioadmin
#      - AWS_REGION=us-east-1
#    ports:
#      - 8888:8888
#      - 8080:8080
#      - 10000:10000
#      - 10001:10001
